services:
  backend:
    container_name: vtype-backend
    build: .
    init: true
    env_file:
      - ./backend/.env
    ports:
      - "8443:8443"
      - "6969:6969"
    restart: unless-stopped
    stop_grace_period: 60s
